version: 2
jobs:
  build:
    working_directory: ~/ews-clojure
    docker:
      - image: circleci/clojure:lein-2.9.1
    environment:
      LEIN_ROOT: nbd
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: ews-clojure-{{ checksum "project.clj" }}
      - run: lein deps
      - save_cache:
          paths:
            - ~/.m2
          key: ews-clojure-{{ checksum "project.clj" }}
      - run: lein do test, uberjar
